### ISSUE TITLE
How to get a subreddit's icon, member count, etc???

### ISSUE THREAD

**Issue by witherBattler** [davidalvarezr/reddit-explorer#27]
The title.

Is there a way with this package to get a subreddit's data, not about the posts but about its data such as the member count?

**Comment by davidalvarezr** [comment]
Hello @witherBattler ,
Yes, but the subreddit must have at least one element. then you can have the member count by doing so:

```ts
    const result = await reddit.getSubreddit({
        name: "news",
        sortMethod: SortingMethod.New,
    })

    console.log(result.data.children[0].data.subreddit_subscribers)
```

Hope it helps

**Comment by witherBattler** [comment]
Okay, thanks a lot
